var fs = require("fs");
var spotifyweights = require("../server/source/spotifyweights");

var myArtists = {"spotify:artist:7LAucJAvbQa7ZIA0qP8YI2":{"name":"The Royal Concept","count":13},"spotify:artist:5Apl0wL4OwNUDYkx69rMDQ":{"name":"Dirty Loops","count":12},"spotify:artist:2IeJDVm6dDYzAXk4aXHVor":{"name":"A treehouse wait","count":4},"spotify:artist:7arnirEq5nMdfa4WxJQKW2":{"name":"A treeouse wait","count":1},"spotify:artist:7hpcX3zORb79qaPYgwkXbi":{"name":"Matt Stinton","count":1},"spotify:artist:26T4yOaOoFJvUvxR87Y9HO":{"name":"Bethel Music","count":25},"spotify:artist:3EwEPyeCmY05Q3zBcjGxrF":{"name":"Steffany Frizzell Gretzinger","count":2},"spotify:artist:6jZbQXvNtDjnj18yoHMuvi":{"name":"Jeremy Riddle","count":6},"spotify:artist:0cuW2lF0YWb9VUyHOnvnsO":{"name":"Jenn Johnson","count":5},"spotify:artist:7qTSoObqlJkIybERfumbQ9":{"name":"Brian Johnson","count":9},"spotify:artist:3cafXZGy8lVX2LJt7wdKVd":{"name":"Hunter G K Thompson","count":1},"spotify:artist:0Onvkz1Nbs4wHXXUwOIGk8":{"name":"Jesus Culture","count":10},"spotify:artist:6quzlF6C6qFyrSCJgkmbaz":{"name":"gustafemanuel.","count":5},"spotify:artist:74cb3MG0x0BOnYNW1uXYnM":{"name":"Hillsong United","count":79},"spotify:artist:4KXp3xtaz1wWXnu5u34eVX":{"name":"Kent","count":25},"spotify:artist:0Uj2hge2fxypJ7f4ik6lpr":{"name":"Blindside","count":22},"spotify:artist:73hSbuO7zeiAnHpkyhQN5P":{"name":"Matt Gilman","count":6},"spotify:artist:2gXmjQIxCO8lMnSncluZaU":{"name":"Cory Asbury","count":6},"spotify:artist:3GBPw9NK25X1Wt2OUvOwY3":{"name":"Jack Johnson","count":14},"spotify:artist:7jy3rLJdDQY21OgRLCZ9sD":{"name":"Foo Fighters","count":13},"spotify:artist:1SaELUYn7deVoQ9kGDGUD9":{"name":"Rebecca St. James","count":15},"spotify:artist:3XHO7cRUPCLOr6jwp8vsx5":{"name":"alt-J","count":25},"spotify:artist:4tZwfgrHOc3mvqYlEYSvVi":{"name":"Daft Punk","count":13},"spotify:artist:6MFopqejpmTUUZlcRmGzgg":{"name":"Todd Edwards","count":1},"spotify:artist:1rAv1GhTQ2rmG94p9lU3rB":{"name":"Julian Casablancas","count":1},"spotify:artist:1R84VlXnFFULOsWWV8IrCQ":{"name":"Panda Bear","count":1},"spotify:artist:2RdwBSPQiwcmiDo9kixcl8":{"name":"Pharrell Williams","count":2},"spotify:artist:3yDIp0kaq9EFKe07X1X2rz":{"name":"Nile Rodgers","count":1},"spotify:artist:1LKElVPBhe0BasoUXWalJH":{"name":"Paul Williams","count":1},"spotify:artist:6pRi6EIPXz4QJEOEsBaA0m":{"name":"Chris Tomlin","count":22},"spotify:artist:6S58b0fr8TkWrEHOH4tRVu":{"name":"Switchfoot","count":59},"spotify:artist:1vCWHaC5f2uS3yhpwWbIA6":{"name":"Avicii","count":12},"spotify:artist:1m6eWfbCoXdPgaCku3HqN8":{"name":"Wiliam Matthews","count":1},"spotify:artist:6xzvt1VigDuN3Qt39YozYA":{"name":"William Matthews","count":1},"spotify:artist:6XyY86QOPPrYVGvF9ch6wz":{"name":"Linkin Park","count":14},"spotify:artist:7m4gF38CPATtHrk5HS42WZ":{"name":"Hillsong Young & Free","count":15}};

var concerts = JSON.parse(String(fs.readFileSync("server/data/concerts.json")));


console.log(spotifyweights.calculateWeights(concerts, myArtists));

